# Generated by Django 5.1 on 2024-08-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='modifiled_date',
            new_name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_jioned',
        ),
        migrations.AddField(
            model_name='user',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'restaurant'), (2, 'customer')], null=True),
        ),
    ]
